server:
  address: localhost
  port: 8000
  fetch_from: https://gorest.co.in/public/v1/posts
  pages: 5

db:
  address: localhost
  port: 5432
  username: postgres
  password: 1029384756
  db_name: demo
  max_attempts: 50