server:
  address: 127.0.0.1
  port: 8000
  fetch_from: https://gorest.co.in/public/v1/posts
  pages: 50

db:
  address: 127.0.0.1
  port: 5432
  username: postgres
  password: 1029384756
  db_name: demo
  max_attempts: 5